/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proposalsManager;

import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author user
 */
public class ProposalsManagerGUI extends javax.swing.JFrame {

    ProposalsGUI proposalsGUI = new ProposalsGUI();    
    
    /**
     * Creates new form ProposalsManagerGUI
     */
    public ProposalsManagerGUI() {
        initComponents();
    }
    
    public void refreshProposalsList() {
        DefaultListModel listModel = new DefaultListModel();
        
        //System.out.println ("="+ProposalsManager.proposalCount);
        for (int c = 0; c < ProposalsManager.proposals.size(); c++) {
            listModel.addElement(ProposalsManager.proposals.get(c).toString());
            //System.out.println (":"+ProposalsManager.proposals[c].toString());
        }
        proposalsList.setModel(listModel);
        try { proposalsList.setSelectedIndex(0); } catch (Exception e) { }
    }    
    
    public void refreshFlash()             
    {
        //System.out.println("Flash:"+ProposalsManager.flash.get());        
        jFlash.setText(ProposalsManager.flash.get());
    }
    
    public void refresh()             
    {
        refreshFlash();
        refreshProposalsList();        
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        proposalsManagerPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        proposalsList = new javax.swing.JList();
        jButtonNew = new javax.swing.JButton();
        jButtonView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jProposalsRequiredLabel = new javax.swing.JLabel();
        jButtonAddDetail = new javax.swing.JButton();
        jFlash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jScrollPane1.setViewportView(proposalsList);

        jButtonNew.setText("new");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        jButtonView.setText("reviews");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Proposals");

        jProposalsRequiredLabel.setText("*");

        jButtonAddDetail.setText("add detail");
        jButtonAddDetail.setEnabled(false);
        jButtonAddDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddDetailActionPerformed(evt);
            }
        });

        jFlash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jFlash.setForeground(new java.awt.Color(153, 102, 0));

        javax.swing.GroupLayout proposalsManagerPanelLayout = new javax.swing.GroupLayout(proposalsManagerPanel);
        proposalsManagerPanel.setLayout(proposalsManagerPanelLayout);
        proposalsManagerPanelLayout.setHorizontalGroup(
            proposalsManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(proposalsManagerPanelLayout.createSequentialGroup()
                .addGroup(proposalsManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNew)
                    .addComponent(jLabel2)
                    .addComponent(jFlash))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(proposalsManagerPanelLayout.createSequentialGroup()
                .addGroup(proposalsManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proposalsManagerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProposalsRequiredLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(proposalsManagerPanelLayout.createSequentialGroup()
                        .addComponent(jButtonAddDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonView)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        proposalsManagerPanelLayout.setVerticalGroup(
            proposalsManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proposalsManagerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFlash)
                .addGap(15, 15, 15)
                .addComponent(jButtonNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(proposalsManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(proposalsManagerPanelLayout.createSequentialGroup()
                        .addComponent(jProposalsRequiredLabel)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, proposalsManagerPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(proposalsManagerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonView)
                    .addComponent(jButtonAddDetail))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proposalsManagerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proposalsManagerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
                    
        if (proposalsList.getSelectedValue() == null) {
            jProposalsRequiredLabel.setForeground(Color.red);            
            return;
        }          
            
        int index = proposalsList.getSelectedIndex();
        Proposal proposal = ProposalsManager.proposals.get(index);
        ProposalReviewsGUI proposalReviewsGUI = new ProposalReviewsGUI(proposal);         
        proposalReviewsGUI.setVisible(true);
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        proposalsGUI.setVisible(true);
    }//GEN-LAST:event_jButtonNewActionPerformed

    private void jButtonAddDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDetailActionPerformed
        // TODO add your handling code here:
        return;
    }//GEN-LAST:event_jButtonAddDetailActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //System.out.println("formWindowActivated");
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        //System.out.println("formWindowLostFocus");
        ProposalsManager.flash.clear();
        refreshFlash();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProposalsManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProposalsManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProposalsManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProposalsManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProposalsManagerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDetail;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jFlash;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jProposalsRequiredLabel;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList proposalsList;
    private javax.swing.JPanel proposalsManagerPanel;
    // End of variables declaration//GEN-END:variables
}
