/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proposalsManager;

import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import static proposalsManager.ProposalsManager.proposals;
import static proposalsManager.ProposalsManager.proposalsManagerGUI;

/**
 *
 * @author brent
 */
public class ProposalReviewGUI extends javax.swing.JFrame {
    
    ProposalReviewsGUI proposalReviewsGUI; // needs reference to parent screen
    Proposal proposal;
    ProposalApplicableReview proposalRequiredReview;

    /**
     * Creates new form ProposalsGUI
     */
    public ProposalReviewGUI(ProposalReviewsGUI proposalReviewsGUI, Proposal proposal, ProposalApplicableReview proposalRequiredReview) {
        initComponents();        
        this.proposal =  proposal;
        updateProposalInfo();        
        this.proposalRequiredReview = proposalRequiredReview;
        updateReviewInfo();

        //TODO if ( !this.proposalRequiredReview.getReview().reviewComponents.containsKey(ReviewDecision.class)) { this.jDecisionPanel.setVisible(false); } // XXX
        this.proposalReviewsGUI = proposalReviewsGUI;
    }
    
    public void updateProposalInfo()
    {
        this.jProposalInfo.setText(this.proposal.toString());
    }
    
    public void updateReviewInfo()
    {
        this.jReviewInfo.setText(this.proposalRequiredReview.toString());
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProposalInfo = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComments = new javax.swing.JTextArea();
        jReviewInfo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jQuery = new javax.swing.JTextArea();
        jDecisionPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDecisionApprove = new javax.swing.JRadioButton();
        jDecisionReject = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jDelegator = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 346));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Proposal");

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel7.setText("Review:");

        jProposalInfo.setText("proposalInfo");

        jButtonSubmit.setText("submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jComments.setColumns(20);
        jComments.setRows(5);
        jScrollPane1.setViewportView(jComments);

        jReviewInfo.setText("reviewInfo");

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel8.setText("Query?");

        jQuery.setColumns(20);
        jQuery.setRows(5);
        jScrollPane2.setViewportView(jQuery);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setText("Decision:");

        buttonGroup1.add(jDecisionApprove);
        jDecisionApprove.setLabel("Approved");
        jDecisionApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDecisionApproveActionPerformed(evt);
            }
        });

        buttonGroup1.add(jDecisionReject);
        jDecisionReject.setLabel("Rejected");
        jDecisionReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDecisionRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDecisionPanelLayout = new javax.swing.GroupLayout(jDecisionPanel);
        jDecisionPanel.setLayout(jDecisionPanelLayout);
        jDecisionPanelLayout.setHorizontalGroup(
            jDecisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDecisionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDecisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jDecisionApprove)
                    .addComponent(jDecisionReject))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jDecisionPanelLayout.setVerticalGroup(
            jDecisionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDecisionPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jDecisionApprove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDecisionReject)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setText("Delegator?");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jLabel4.setText("Enter delegator if relevant");

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel9.setText("Comments");

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 2, 12)); // NOI18N
        jLabel5.setText("Enter query if relevant");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jProposalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubmit)
                    .addComponent(jReviewInfo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(43, 43, 43)
                                    .addComponent(jLabel5))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDecisionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDelegator, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProposalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jReviewInfo)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDecisionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDelegator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButtonSubmit)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        
        ProposalReviewData proposalReviewData = new ProposalReviewData();
        ProposalReviewData reviewGeneralInfo = new ProposalReviewData(ReviewGeneralInfo.class);
        reviewGeneralInfo.add(new ProposalReviewComponentItem("comments",jComments.getText()));
        reviewGeneralInfo.add(new ProposalReviewComponentItem("delegator",new UserId(jDelegator.getText())));
        proposalReviewData.add(reviewGeneralInfo);
        ProposalReviewData reviewQuery = new ProposalReviewData(ReviewQuery.class);
        reviewQuery.add(new ProposalReviewComponentItem("query",jQuery.getText()));        
        proposalReviewData.add(reviewQuery);        
        ProposalsManager.proposals.get(0).submitReview(ProposalsManager.proposals.get(0).getProposalApplicableReviews().get(0), proposalReviewData);        
        Decision decision = null;
        if (jDecisionApprove.isSelected()) decision = new Decision(Decision.Literal.Approved);
        else if (jDecisionReject.isSelected()) decision = new Decision(Decision.Literal.Rejected);
        ProposalReviewData reviewDecision = new ProposalReviewData(ReviewDecision.class);
        reviewDecision.add(new ProposalReviewComponentItem("decision", decision));
        proposalReviewData.add(reviewDecision);        

        try
        {
            this.proposal.submitReview(this.proposalRequiredReview, proposalReviewData);
        } catch (Exception e) { System.out.println(e); }
                
        this.setVisible(false);
        this.dispose();
        this.proposalReviewsGUI.setVisible(true);
        this.proposalReviewsGUI.updateProposalApplicableReviewsList();
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jDecisionApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDecisionApproveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDecisionApproveActionPerformed

    private void jDecisionRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDecisionRejectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDecisionRejectActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JTextArea jComments;
    private javax.swing.JRadioButton jDecisionApprove;
    private javax.swing.JPanel jDecisionPanel;
    private javax.swing.JRadioButton jDecisionReject;
    private javax.swing.JTextField jDelegator;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jProposalInfo;
    private javax.swing.JTextArea jQuery;
    private javax.swing.JLabel jReviewInfo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
